### ISSUE TITLE
hello help me please help me

### ISSUE THREAD

**Issue by vanojk1** [bbfh-dev/bubblellaneous-pack#12]
hello. I used your datapack and after a while it started overloading my server with friends. I want to delete it now, but the datapack is not being deleted. I tried "/function bubblellaneous:uninstall". but the furniture is not being removed.
Datapack Name: Bubblellaneous
Download location: https://minecraft-inside.ru/data-packs/152246-bubblellaneous.html

waiting for an answer

Здравствуйте. пользовался вашим датапаком и через какое то время он начал перегружать мой сервер с друзьями. сейчас хочу удалить но датапак не удаляется. пробовал "/function bubblellaneous:uninstall". но мебель не удаляется.
Название датапака: Bubblellaneous 
Место скачивания: https://minecraft-inside.ru/data-packs/152246-bubblellaneous.html
Помогите пожалуйста.

**Comment by bbfh-dev** [comment]
bubblellaneous that you have installed is an outdated 3-years old version. Not to mentioned that **I never posted it on "minecraft-inside.ru"**, the link you are referencing is someone else re-uploading my work.

You can delete all furniture blocks by using `/kill @e[tag=bubblellaneous]`

**Comment by vanojk1** [comment]
thank you, I will check and I will unsubscribe
