### ISSUE TITLE
German translation?

### ISSUE THREAD

**Issue by Atten007** [bbfh-dev/bubblellaneous-pack#16]
Hello,

I'm very interested to provide you a German translation for your data pack! If you can tell me how I can do that, it'll be really nice! I'm from Germany so I can translate the entire pack if you want.

Greetings,
Atten007 😊

**Comment by bbfh-dev** [comment]
You can find the translation .csv file here: [Google Docs](https://docs.google.com/spreadsheets/d/1EUnWG0IqMqeK9gWmoUMSMg64dMkOG856WHP-3A6NOUk/edit?usp=sharing).

If you provide me your email (in here or on discord) I can give you access to the document. Otherwise feel free to edit it locally and then send me the file/link.

**Comment by bbfh-dev** [comment]
\*misclick

**Comment by Atten007** [comment]
> You can find the translation .csv file here: [Google Docs](https://docs.google.com/spreadsheets/d/1EUnWG0IqMqeK9gWmoUMSMg64dMkOG856WHP-3A6NOUk/edit?usp=sharing).
> 
> If you provide me your email (in here or on discord) I can give you access to the document. Otherwise feel free to edit it locally and then send me the file/link.

Okay, please write me at: mail@mika-kreis.de.

**Comment by bbfh-dev** [comment]
I sent the access to your email, you should receive a link that lets you edit the file.

**Comment by Atten007** [comment]
> I sent the access to your email, you should receive a link that lets you edit the file.

Thanks! I’ll start translating it tomorrow! 😊

**Comment by Atten007** [comment]
> I sent the access to your email, you should receive a link that lets you edit the file.

But I’m only in reading mode.

**Comment by bbfh-dev** [comment]
Alright, should be fixed now

**Comment by Atten007** [comment]
Hello,

I finished the German translation for your data pack. You can find them [here](https://docs.google.com/spreadsheets/d/1EUnWG0IqMqeK9gWmoUMSMg64dMkOG856WHP-3A6NOUk/).

Kind regards,
Atten007 😊

**Comment by bbfh-dev** [comment]
Alright, thank you! ❤️ It will be added within the next few minutes in version 2.1.2
