### ISSUE TITLE
Items disappearing when accidentaly placed in bubble bench 

### ISSUE THREAD

**Issue by TazzerYT** [bbfh-dev/bubblellaneous-pack#19]
When items are placed into the bubble bench they disappear rather than going back into your inventory.

**Comment by bbfh-dev** [comment]
It's something that would take too much effort to change because of how minecraft works. If someone else wants to update it they are free to do so, but I'm only doing maintenance on this datapack and won't add any new features (since I was only paid to do so)

**Comment by bbfh-dev** [comment]
Feel free to reopen this issue if any questions occur

**Comment by bbfh-dev** [comment]
Feel free to reopen this issue if any questions occur
