### ISSUE TITLE
TexturePack

### ISSUE THREAD

**Issue by AlexVin-Dev** [bbfh-dev/bubblellaneous-pack#2]
![image](https://user-images.githubusercontent.com/15629077/221372585-415c0b3e-bb9c-40fe-8af8-b504ba407778.png)
Texture pack does not display some elements on 1.19.3

**Comment by bbfh-dev** [comment]
Thanks for reporting the issue. The bug was fixed in version `1.2c` ([Download Here](https://modrinth.com/datapack/bubblellaneous/version/1.2c)).
