### ISSUE TITLE
Translation Assist to Spanish

### ISSUE THREAD

**Issue by Starsoon** [bbfh-dev/bubblellaneous-pack#20]
Hey there! I've been using your datapack for a while now, and it's amazing! I noticed that Spanish, my main language, is missing. I would love to help by translating it into Spanish, so more users like me can enjoy it. If you are interested let me know!

**Comment by bbfh-dev** [comment]
Bubblellaneous will not receive any updates (at least from me)**[1]**. However if you still want to create a Spanish translation:
- [Google Spreadsheets](https://docs.google.com/spreadsheets/d/1EUnWG0IqMqeK9gWmoUMSMg64dMkOG856WHP-3A6NOUk/edit?usp=sharing)
- [Bubblellaneous Translations - lang.csv](https://github.com/user-attachments/files/18101933/Bubblellaneous.Translations.-.lang.csv) (Download file)

You can send the file back with your edits

> \* [1] I updated the datapack to 1.21 as I was paid to do so, I do not have any motivation to continue working on Minecraft content for free. I can still add the new translation, **but the datapack might at some point become outdated**.

**Comment by Starsoon** [comment]
Thanks for getting back to me! It's a shame it won't receive any updates, but at least Bubblellaneous now has another language available. I added 3 variants for Spanish: ES_ES, ES_MX and ES_CL.

- [Bubblellaneous.Translations.-.lang.csv](https://github.com/user-attachments/files/18170172/Bubblellaneous.Translations.-.lang.csv)

I appreciate the opportunity to contribute. Have a great day!

**Comment by bbfh-dev** [comment]
Thanks for your contribution! Expect it to be added in 2.1.6
